import './Home.css'

const Home = () => {
  return (
    <div>
      <div className="intro-section">
        <h1 className="name">Hello, I'm Ivy</h1>
        <h2 className="tagline">Software Developer</h2>
        <p className="description">
          Welcome to my portfolio! I'm a proactive and result-driven software developer, with experience in both front-end and back-end technologies. 
          I focus on building clean, efficient apps and enjoy solving problems with intuitive, user-friendly designs.
        </p>
        <p className="description">
          Explore my projects, and feel free to get in touch if you have any questions or opportunities to collaborate!
        </p>
        <p className="description">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam a vehicula ligula. Phasellus posuere, diam vel maximus ultricies, ipsum tortor dapibus dolor, quis tincidunt tortor sapien et libero. Fusce vulputate tincidunt ex. Mauris imperdiet ante sit amet porta hendrerit. Vestibulum sed diam est. Quisque semper auctor orci, vel lobortis velit rhoncus eget. Mauris ante diam, eleifend ut lacus ut, maximus hendrerit nisi. Vestibulum imperdiet est sit amet erat pretium, ac malesuada massa consequat. Etiam iaculis convallis dolor. Donec scelerisque porttitor dui, eu gravida enim. Nulla consectetur neque sed urna molestie, vel convallis nisl ultrices. Pellentesque iaculis turpis mauris, sit amet hendrerit eros placerat et. Nam at ultrices quam, vel blandit dolor. Fusce lacus ante, interdum quis rutrum et, lobortis sed erat. Duis eget dui cursus, vestibulum nulla non, ultrices elit.

Vestibulum accumsan bibendum felis at lacinia. Maecenas pellentesque, ex ut suscipit fringilla, ipsum turpis placerat tortor, nec placerat tortor justo posuere nulla. Mauris at posuere leo. Maecenas sodales sapien et eros laoreet faucibus. Etiam gravida at nisl sed convallis. Aenean lectus diam, scelerisque et sem ut, sodales tincidunt libero. Vestibulum vitae facilisis sapien. Aliquam erat volutpat. Praesent non dolor accumsan, placerat sapien sit amet, eleifend massa.

Aliquam a neque fringilla nisl rhoncus fringilla eu vel mi. Etiam sed dignissim quam. Donec at egestas nunc, ut tempus ante. Vivamus dui mauris, varius ut risus eget, ornare ornare risus. Donec at mollis tortor. Duis vitae justo sed ex consectetur scelerisque. Ut a interdum ante. Nullam varius purus eget massa tincidunt, id tristique arcu auctor. Vivamus eros ex, suscipit non sollicitudin at, fringilla id lorem.

Praesent hendrerit, sem at pellentesque luctus, massa risus accumsan quam, et ultricies sapien ex in dui. Suspendisse sagittis leo pulvinar, vestibulum felis ac, blandit velit. Sed tempus aliquet pretium. Vestibulum molestie tellus id tempus tempor. Curabitur eu urna et orci ultrices dapibus. Suspendisse tincidunt sem a dui egestas porttitor. Donec condimentum rhoncus tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Suspendisse nec ultrices mi. In fringilla erat vulputate ultricies porta. Sed mi velit, finibus nec molestie non, auctor vitae arcu. Vestibulum auctor lacinia vestibulum. Nunc eleifend quis massa vitae consequat. Mauris pellentesque pretium velit. Donec hendrerit ante vitae malesuada tincidunt. Maecenas imperdiet odio sit amet urna tincidunt tristique. Fusce rhoncus mattis enim faucibus consectetur. Cras sit amet orci tortor. Proin sit amet tempor elit. Praesent aliquam volutpat est, et ornare sapien tristique in. In pretium turpis sit amet lectus placerat, rutrum scelerisque dui mattis. Nullam eget semper ligula, in dictum tellus.

Nullam congue et elit sed mattis. In hac habitasse platea dictumst. Phasellus consequat auctor ligula, ut posuere ligula congue ac. Phasellus et condimentum enim. Duis lacinia justo sagittis tempus ultricies. Sed sed leo eu lectus tempor tincidunt eget at est. Aenean et elementum urna. Nulla mollis ipsum at blandit sagittis. Donec a tellus dictum, suscipit purus et, convallis massa. Ut vel maximus lorem.

Praesent feugiat sed dolor et venenatis. Vestibulum egestas velit mauris, suscipit lacinia nisi euismod et. Proin congue vulputate metus non tincidunt. Vivamus ultricies tincidunt quam, a consectetur mi consequat nec. Suspendisse accumsan laoreet mauris et sodales. Morbi vel imperdiet dui. Praesent mauris nisi, dapibus non blandit nec, gravida non nisl. Fusce mattis sed magna eget elementum.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla eu est vulputate, rutrum nibh quis, ornare ex. Donec ut elementum leo, id congue arcu. Ut in quam felis. Vestibulum dignissim, leo vehicula imperdiet rutrum, metus leo molestie neque, nec interdum orci augue vel sem. Morbi ante massa, mattis nec semper nec, placerat eget est. Aenean a odio euismod, luctus elit in, convallis mi. Praesent malesuada massa leo, eget ultricies lorem fringilla eu. Morbi eu convallis sapien. Etiam vehicula sit amet risus sit amet convallis. Donec leo tellus, lacinia eget hendrerit ac, lobortis faucibus nunc. Vestibulum vulputate dolor nulla, eget fringilla urna tempor eget.

Aliquam quis magna in neque ullamcorper ultricies. Pellentesque ornare imperdiet eros, non egestas turpis faucibus non. Vestibulum bibendum, felis in mollis vehicula, nisl magna consequat massa, eget efficitur ligula nisi non nisi. Nam non tortor a tellus ultricies volutpat. Cras bibendum finibus orci sed malesuada. Nam varius est vitae odio blandit aliquam. In nunc lorem, blandit ac sem ac, sodales blandit eros. Phasellus tempor nisl nisi, id egestas nisi ullamcorper id.

Proin nec sollicitudin leo, eget congue ligula. Proin interdum, magna in cursus iaculis, orci mi vestibulum augue, eu euismod erat ipsum sed est. Nullam vitae ex eu quam dapibus suscipit vel vel leo. Phasellus a sapien facilisis, dignissim lectus quis, vulputate enim. Nulla et pretium sapien. Nunc nec eros in nunc dignissim iaculis. Maecenas dictum sapien condimentum, tempus metus vel, consequat nunc. Pellentesque convallis pulvinar ipsum, eu varius elit lacinia elementum. Cras mollis tempus fermentum. Nunc porttitor dolor vitae hendrerit aliquam. Mauris vel neque sem. Mauris sed mi a est faucibus volutpat. Suspendisse potenti. Nulla in sodales eros, quis molestie augue.

Praesent imperdiet sagittis dui, a gravida enim volutpat sit amet. Integer quam orci, pulvinar id viverra blandit, scelerisque semper lacus. Suspendisse justo nunc, molestie et est a, rhoncus dictum tortor. Praesent sit amet odio vel eros viverra consectetur. Sed ac bibendum magna, et volutpat nunc. Aliquam quis justo vulputate erat ornare hendrerit. In at ultrices erat, sit amet dapibus risus. Aliquam scelerisque, nunc sit amet pellentesque accumsan, purus lacus aliquam erat, ac facilisis felis elit id sem. Donec nec purus neque. Phasellus eget eros tincidunt, venenatis magna at, facilisis risus. Pellentesque sit amet convallis dui. Fusce ut nulla lectus.

Vestibulum vel molestie ex. Praesent eu dui ut augue faucibus tristique vel cursus magna. Proin non erat sagittis, semper sapien a, rutrum mauris. Etiam aliquam feugiat quam, sit amet scelerisque elit sollicitudin a. Suspendisse aliquet turpis vel nunc semper, a facilisis sem condimentum. Nulla nec aliquet justo. Phasellus sed neque at massa mollis sagittis iaculis in lectus. Suspendisse rutrum orci sed dignissim gravida. Nam sollicitudin velit sed auctor placerat. Nulla imperdiet leo pellentesque euismod sagittis. Quisque non mollis dolor. Mauris ac diam non neque consequat faucibus eu ac eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Integer augue ligula, congue in ultrices vitae, convallis ut tellus. Maecenas et feugiat neque. Proin dapibus velit et dui condimentum porta. Phasellus ornare vel massa vitae lobortis. Donec malesuada odio mi, nec elementum tellus pellentesque ac. Donec dolor erat, venenatis vel massa sit amet, posuere bibendum sapien. Sed blandit mollis lacus, aliquam imperdiet augue lobortis ac. Pellentesque at egestas ipsum. Cras eu eros turpis. Integer vitae laoreet neque. Mauris massa augue, laoreet et metus eu, tincidunt gravida eros. Etiam est erat, interdum in condimentum non, elementum luctus mi. Phasellus tincidunt purus et nibh bibendum, eu viverra dui gravida. Nunc pharetra nulla nunc, eu aliquam justo accumsan non.

Donec imperdiet diam quis quam finibus consequat. Donec nec elit sit amet mauris faucibus faucibus eu eget elit. Integer mollis at quam sit amet rutrum. Pellentesque non tincidunt ligula. Praesent pretium augue eu massa tempus rutrum. Nulla feugiat nisi quam, vitae mollis sem bibendum ac. In maximus a turpis nec porta. Ut porta pulvinar elit eget euismod. Aliquam congue lectus id tincidunt ullamcorper. Morbi eleifend iaculis posuere. Morbi tristique elementum elit, sed ornare dolor placerat at.

Pellentesque non pretium elit. Phasellus imperdiet massa vehicula, aliquam dui et, sodales tortor. Ut aliquam mauris aliquam ex rutrum hendrerit. In hac habitasse platea dictumst. Nulla non nisi et nunc tempor vulputate vitae eget sapien. Nulla lobortis nisi metus, ut commodo ex ornare posuere. Maecenas a massa a ipsum pulvinar egestas. Phasellus eu elit nec odio euismod mattis vitae eget risus.

Cras vitae luctus velit. Pellentesque euismod erat id orci blandit tincidunt. Donec vestibulum magna non vulputate pellentesque. Phasellus turpis odio, aliquet gravida risus sed, sodales tincidunt mi. In venenatis augue eu neque sollicitudin dapibus. Mauris semper pellentesque enim eu rhoncus. Vivamus interdum massa at pellentesque accumsan. In hac habitasse platea dictumst.

Aliquam id placerat nisi, vitae porttitor magna. Fusce dictum velit faucibus velit consectetur fermentum venenatis quis nunc. In justo turpis, sollicitudin a sagittis ut, elementum non lacus. Duis dignissim pulvinar mauris et hendrerit. Vestibulum hendrerit semper ipsum, quis elementum quam vulputate et. Duis consequat ante at eleifend maximus. Proin diam dui, tincidunt quis odio in, sollicitudin euismod neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla viverra blandit hendrerit. Quisque feugiat lectus orci, et ultricies ante varius a. Nunc molestie molestie quam in consectetur. Sed pretium congue nisl at varius. Nulla sed nibh nec est blandit tempor. Vivamus et tortor leo. Vestibulum sapien mauris, faucibus quis feugiat vel, porta nec nulla. Ut sed erat id lacus lacinia pharetra non id elit.

Proin a facilisis leo. Sed nec purus nulla. Sed lobortis porta nibh, et fermentum urna pharetra eu. Proin nulla arcu, viverra vitae leo a, ultrices scelerisque leo. In porttitor accumsan nisi et iaculis. Etiam quis aliquam nibh, in vehicula lorem. Suspendisse scelerisque iaculis mauris, sed aliquet neque consequat non. Pellentesque in sapien et massa tristique bibendum efficitur ut augue.

Donec gravida non nulla in fringilla. Ut iaculis auctor arcu ac vestibulum. Proin elementum quam at cursus dignissim. Curabitur lacus turpis, posuere ac ipsum ut, condimentum congue nunc. Vestibulum quam dolor, fringilla quis scelerisque ac, egestas vel enim. Quisque convallis velit a urna iaculis, eget dignissim augue semper. Suspendisse eget tortor in enim interdum imperdiet et vel arcu. In aliquam scelerisque consequat. Vestibulum nibh odio, pulvinar sit amet vestibulum a, placerat consectetur lacus.

In egestas eget magna et aliquet. Phasellus pellentesque congue neque eu molestie. Etiam pellentesque maximus tortor, sed iaculis neque varius vitae. Sed vitae massa arcu. Maecenas libero ligula, dapibus bibendum sodales at, fermentum ut lorem. Maecenas bibendum massa sit amet arcu lobortis euismod. Phasellus condimentum placerat erat luctus malesuada. Sed eu quam sit amet dolor tincidunt sodales nec condimentum lectus.

Ut risus lacus, finibus sit amet est a, ullamcorper facilisis velit. Maecenas viverra auctor metus eu vulputate. Aenean molestie tincidunt porttitor. Vestibulum eu leo tempor, tristique arcu a, faucibus ex. Sed congue elit mollis magna efficitur, hendrerit rhoncus nisl tincidunt. Sed sit amet neque ultricies erat lobortis consequat eget ac magna. Proin eu mauris at ante feugiat semper non quis erat. Vivamus semper, ex quis dictum euismod, libero turpis ornare augue, at ultrices ipsum enim porttitor lectus. Sed at accumsan tellus, eu laoreet ante. Suspendisse non eleifend lacus.

Fusce scelerisque sem nec est tempus, vel pellentesque odio blandit. Etiam imperdiet placerat elit. Sed porttitor, orci a venenatis tempor, lorem purus posuere leo, eget pharetra est justo a magna. Mauris ultricies vitae tellus rhoncus fermentum. Etiam gravida, dui eget malesuada vulputate, lectus nisl blandit quam, quis tempus nulla dui vitae purus. Fusce porta leo gravida velit gravida, sit amet finibus lectus luctus. Aenean accumsan massa vitae cursus porta. Suspendisse elementum, sapien sed rhoncus ornare, augue turpis dignissim neque, in vehicula risus erat in dui. Proin sed odio mi.

Nunc interdum, erat a vehicula pellentesque, ex ligula imperdiet urna, ullamcorper congue lorem justo nec lorem. Quisque pharetra imperdiet nisl, porttitor consequat tortor consequat id. Maecenas quis condimentum nibh. Donec pretium rutrum dolor. Phasellus at accumsan felis. Praesent in est ultricies purus elementum luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis tortor sit amet placerat volutpat.

Cras sed urna scelerisque, aliquam sapien et, accumsan tortor. In vitae bibendum eros. Nullam rhoncus dui vitae sapien feugiat placerat. Nullam ac libero et mi fermentum cursus. Praesent rutrum nibh ac maximus finibus. Nulla facilisi. Nam ultrices magna ut iaculis lacinia.

Nunc sit amet dolor tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In varius vehicula est, quis volutpat dolor fermentum in. Curabitur blandit, lorem non lobortis volutpat, enim orci luctus nisi, non gravida metus diam et erat. Donec ac turpis vitae sem varius posuere ut eget dolor. Ut eu eros sit amet arcu interdum luctus ut non magna. Vivamus id libero sed mauris cursus fringilla ut id ex. Quisque et justo a justo lobortis dapibus. Mauris scelerisque efficitur pulvinar. Suspendisse eget nisi vel odio varius posuere porttitor ut magna. Phasellus tristique massa justo, ut accumsan arcu dapibus consectetur.
        </p>
      </div>
    </div>
  )
}

export default Home
